###peticion get
get http://localhost/proyecto-apiCrud/backend-apiCrud/operaciones

###peticion post - verificar un usuario
Post http://localhost/proyecto-apiCrud/backend-apiCrud/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "admin12345"
}

###peticion get obtener productos
get http://localhost/proyecto-apiCrud/backend-apiCrud/productos

###peticion post para crear productos
POST http://localhost/proyecto-apiCrud/backend-apiCrud/productos
Content-Type: application/json

{
    "nombre": "Lasagna",
    "descripcion": "Tripe carne",
    "precio": 45000.00,
    "stock": 10,
    "imagen": "https://th.bing.com/th/id/R.4ec607d5ce0a5808dc26d80b2a1da2ec?rik=bZXR31LSCghW8w&pid=ImgRaw&r=0"
}
###peticion post para actualizar productos
PUT http://localhost/proyecto-apiCrud/backend-apiCrud/productos
Content-Type: application/json

{
    "id": 4,
    "nombre": "Lasagna Mixta",
    "descripcion": "Tripe carne",
    "precio": 45000.00,
    "stock": 10,
    "imagen": "https://th.bing.com/th/id/R.4ec607d5ce0a5808dc26d80b2a1da2ec?rik=bZXR31LSCghW8w&pid=ImgRaw&r=0"
}
###peticion post para eliminar productos
DELETE http://localhost/proyecto-apiCrud/backend-apiCrud/productos
Content-Type: application/json

{
    "id": 4
}